name: Build, Scan & Deploy

on:
  push:
    branches:
      - main
    paths:
      - "checkout-api/**"
      - ".github/workflows/deploy.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::906286017981:role/Github-actions-ecr-role
  ECR_REPOSITORY: checkout-api

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Check out code
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Configure AWS credentials using GitHub OIDC
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      # Verify AWS authentication
      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      # Login to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --progress=plain \
            -t "$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" \
            -t "$REGISTRY/$ECR_REPOSITORY:latest" \
            ./checkout-api

      # Scan Image with Trivy
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      # Push Image to ECR
      - name: Push Image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push "$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$REGISTRY/$ECR_REPOSITORY:latest"